"""One-off: generate Paula's CV (+ cover letter) for the Perfetti Van Melle role
at "Perfetti Van Melle Export Middle East & Africa DMCC" (Dubai free-zone entity):

  • E-Commerce Executive — Growth Markets      (posted Jul 29, 2026)

(The sibling "Senior E-Commerce Executive" role was already generated by
scripts/_gen_perfetti_van_melle_senior_ecommerce_executive.py in a prior run —
id perfetti-van-melle-senior-ecommerce-executive-2026-08 — so it is NOT rebuilt
here to avoid a duplicate dashboard entry / package.)

It is an e-retail / e-commerce ACCOUNT-MANAGEMENT role for an FMCG confectionery
leader (Mentos, Chupa Chups, Fruittella, Alpenliebe…): grow strategic e-retail
accounts, own annual budget plans + monthly rolling forecasts with distributors and
country managers, run quarterly assortment reviews, build customer/joint business
plans (joint KPIs), hold SKU availability / service levels >85%, optimise the
customer digital journey, and identify emerging e-commerce growth — liaising between
HQ, country teams and external partners.

Honest context (IMPORTANT):
  - STRONG fit on substance. Paula's core maps almost point-for-point:
      • DoFreeze — grows brands across UAE quick-commerce / e-retail (Noon, Talabat,
        Careem, Deliveroo): onboarding, listings, promo mechanics, retail execution;
        forecasting & A&P budgets; assortment; Shopify + CRO; 6 NPD launches; liaison
        HQ ↔ distributors ↔ country teams across 50+ markets.
      • Miravia (Alibaba) — Key Account Manager on a top-5 marketplace: 42 e-retail
        accounts, +30% GMV QoQ via pricing / assortment optimisation / promotions;
        Flash Sales channel to CEO; 30+ store onboardings as PIC Fragrances. This IS
        the "manage & grow strategic e-retail accounts" mandate.
      • Glovo — quick-commerce account management, retail-vertical onboarding.
      • Mondelez — FMCG CONFECTIONERY (chocolate) category planning: sell-in/sell-out,
        rolling forecasts, assortment & promo effectiveness. Directly relevant to a
        confectionery house like Perfetti.
  - Honest notes, surfaced not hidden:
      1. LEVEL: these are "Executive" / "Senior Executive" roles (they ask 2–3 yrs);
         Paula is 4+ yrs at Manager level — i.e. slightly SENIOR to the band, not short
         of it. Presented as directly-relevant hands-on account experience, not inflated.
      2. Role #1 ("Growth Markets") JD text says "Position based in Lebanon" while the
         Indeed/careers posting is tagged Location: Dubai, AE (the hiring entity is the
         Dubai DMCC). Per Guille's instruction we follow the posting's Dubai tag for the
         location field; the Lebanon nuance is kept in the internal red_flags for honesty.
  - Per project rules: NOTHING fabricated (real titles/metrics). NO "own visa / no
    sponsorship" claim anywhere — the CV visa field ("UAE Residence Visa") is factual;
    the letters assert nothing about sponsorship (her residence visa is employer-paid).

Application channel: Perfetti Van Melle careers portal (SAP SuccessFactors), no named
hiring manager → CONTACT = None, letters addressed to "Hiring Manager".

Fills the real CV + cover-letter templates, converts to PDF via LibreOffice (soffice
headless — docx2pdf/Word fails on this Mac), registers both jobs for the dashboard,
and lands each package under output/2026-08-23/.
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from career_ops.config import settings
from career_ops.discovery.normalize import Job
from career_ops.generators import cover_letter as cl
from career_ops.generators import cv_generator as cv

COMPANY = "Perfetti Van Melle"
DATE_FOLDER = "2026-08-23"
CONTACT = None  # Careers-portal application, no named hiring manager → "Hiring Manager".

# ---------------------------------------------------------------------------
# Shared, honest e-commerce-account-management experience block (both roles).
# ---------------------------------------------------------------------------
SHARED_EXPERIENCE = [
    {
        "company": "DoFreeze LLC",
        "role": "Brand & E-Commerce Manager",
        "dates": "Oct 2025 – Present",
        "location": "Dubai, UAE",
        "context": "Global FMCG distributor | Brands: Befit, Eurocake, Flair | 50+ countries",
        "bullets": [
            "Grow strategic e-retail and quick-commerce accounts across the UAE (Noon, Talabat, Careem, Deliveroo) — onboarding, product listings, promotional mechanics and retail execution — driving sell-out and expanding the digital footprint across 50+ markets",
            "Own annual A&P/budget plans and monthly rolling forecasts jointly with distributors and country teams, keeping inventory and sales aligned, and run quarterly assortment reviews to optimise the product mix",
            "Build customer / joint business plans with e-retail partners (joint KPIs, promo calendars) and safeguard high SKU availability and service levels across accounts",
            "Optimise the customer digital journey and digital shelf — product pages, content, search visibility, CRO on the brand's Shopify store and on marketplaces — using data to lift engagement, conversion and average order value",
            "Lead 6 NPD launches end-to-end (brief, pricing, go-to-market) and run paid media on Meta and Google Ads to capitalise on emerging e-commerce growth opportunities",
            "Act as the liaison between HQ, country managers and external distributors/partners, aligning and executing e-commerce initiatives on time across regional markets",
        ],
    },
    {
        "company": "Miravia (Alibaba Group)",
        "role": "Key Account Manager – Beauty, Fragrances & Fashion (E-Commerce)",
        "dates": "Nov 2023 – Oct 2025",
        "location": "Madrid, Spain",
        "context": "Top-5 global e-commerce marketplace | 100K+ employees",
        "bullets": [
            "Managed and grew 42 e-retail key accounts on a top-5 marketplace, achieving +30% GMV growth QoQ through pricing strategy, assortment optimisation and targeted promotions — the exact 'manage & grow strategic e-retail accounts' mandate",
            "Owned the Flash Sales channel for Beauty, Fashion & Home, reporting directly to the CEO and executing commercial plans aligned to P&L targets",
            "Ran assortment reviews and category expansion as PIC Fragrances, onboarding 30+ new stores in two months via strategic promotions and trend-led products",
            "Continuously analysed ROI, ROAS, conversion, traffic and retention to inform business decisions and sharpen forecasting accuracy",
        ],
    },
    {
        "company": "Glovo",
        "role": "Account Manager – XL Accounts",
        "dates": "Sep 2022 – Nov 2023",
        "location": "Madrid, Spain",
        "context": "Quick-commerce super-app | €500M+ revenue | 10K+ employees",
        "bullets": [
            "Managed strategic key accounts on a quick-commerce platform, driving GMV through data-led planning and bespoke activations, and negotiating high-impact commercial deals",
            "Part of the team building Glovo's retail vertical — onboarding fashion, beauty and lifestyle brands and expanding the marketplace beyond food into non-food e-commerce",
            "Led cross-functional teams (marketing, logistics, support) to deliver campaigns and increase order volume",
        ],
    },
    {
        "company": "Mondelez International",
        "role": "Trainee – Category Planning",
        "dates": "Aug 2021 – Aug 2022",
        "location": "Madrid, Spain",
        "context": "Global FMCG confectionery leader | €36B annual revenue | 90K+ employees",
        "bullets": [
            "Ran sell-in/sell-out analysis, rolling forecasts and promotional-effectiveness reviews for the chocolate category — confectionery FMCG, directly comparable to Perfetti's category",
            "Contributed to NPD launches (Milka Spread, Mini Suchard), sharpening assortment and go-to-market judgement inside a global confectionery leader",
        ],
    },
]

SHARED_SKILLS = {
    "skills_brand": (
        "e-commerce strategy, NPD & go-to-market, promotional planning, A&P/budget "
        "management, trade & shopper marketing, emerging-growth identification"
    ),
    "skills_ecommerce": (
        "quick-commerce (Noon, Talabat, Careem, Deliveroo), e-retailer platforms & "
        "digital marketplaces, e-retailer platform strategy, customer digital journey, "
        "digital shelf, Shopify / e-store, CRO, Meta Ads, Google Ads"
    ),
    "skills_commercial": (
        "e-retail key account management, distributor & country-team coordination, "
        "customer / joint business plans (joint KPIs), annual budget planning, monthly "
        "rolling forecasts, quarterly assortment reviews, SKU availability & service "
        "levels, stakeholder management"
    ),
    "skills_data": (
        "sell-in/sell-out, forecast accuracy, ROI, ROAS, conversion, AOV, P&L, "
        "data-driven decision-making, Power BI, Nielsen, Kantar"
    ),
    "skills_tools": (
        "Shopify, Meta Ads Manager, Google Ads, Salesforce, SAP, Power BI, Nielsen, "
        "Kantar, Generative AI (Claude, ChatGPT), Canva, Microsoft Office (Expert)"
    ),
}

# ---------------------------------------------------------------------------
# Role-specific config.
# ---------------------------------------------------------------------------
ROLES = [
    {
        "id": "pvm-ecom-exec-growth-markets-2026-08",
        "title": "E-Commerce Executive Growth Markets",
        "url": "https://careers.perfettivanmelle.com/",
        "ai_score": 84,
        "ai_tier": "Strong",
        "posted": "Jul 29, 2026",
        "job_description": """\
E-Commerce Executive — Growth Markets. Perfetti Van Melle Export Middle East & Africa
DMCC. Location: Dubai, AE (careers posting tag). FMCG confectionery.

WHAT YOU WILL DO
Strengthen and expand the digital sales presence within priority/growth markets;
manage and grow strategic e-retail accounts aligned with the broader e-commerce
strategy to achieve and exceed sales targets. Dynamic collaboration with internal
teams (E-commerce, Marketing, Country Management) and external partners (distributors,
retail customers) across diverse regional markets.

Key responsibilities:
- Drive budgeted/planned sales targets through proactive account management and sales
  strategy execution.
- Develop and manage comprehensive annual budget plans to support growth and resource
  allocation.
- Lead quarterly assortment reviews with e-retailers to optimise product offerings and
  align with market demand.
- Coordinate monthly rolling forecasts with country managers and distributors to
  maintain sales pipelines and inventory management.
- Create tailored customer business plans with joint planning KPIs, fostering strategic
  partnerships.
- Ensure high SKU availability and service levels above 85%.
- Identify and capitalise on emerging e-commerce opportunities to drive incremental
  growth.
- Implement and enhance the customer digital journey to improve engagement, conversion
  and brand loyalty.
- Continuously analyse market trends, competitor activity and consumer behaviour.
- Act as key liaison between HQ, country teams and external partners.

OUR PERFECT CANDIDATE
- Bachelor's in Business, Marketing, E-commerce or related.
- At least 3 years managing e-commerce accounts (or similar) within FMCG or retail.
- Strategic mindset; strong forecasting and budget-management skills.
- Excellent stakeholder-management, communication and interpersonal skills.
- Strong analytical skills (sales data, market trends, consumer behaviour).
- Familiarity with e-commerce platforms, digital-marketing tools and CRM systems.
- Strong customer focus; English required (additional regional languages an advantage).
""",
        "headline": (
            "E-Commerce Executive · E-Retail Account Growth · Quick-Commerce (Noon · "
            "Talabat · Careem · Deliveroo) · Forecasting & Budget Planning · Assortment "
            "& Trade Planning · FMCG · Dubai, UAE"
        ),
        "professional_summary": (
            "E-commerce and commercial professional with 4+ years growing e-retail "
            "accounts across FMCG, quick-commerce and marketplaces. Currently leads "
            "Brand & E-Commerce for DoFreeze across 50+ markets — growing UAE "
            "quick-commerce accounts (Noon, Talabat, Careem, Deliveroo), owning annual "
            "budget plans and monthly rolling forecasts with distributors and country "
            "teams, running assortment reviews and safeguarding SKU availability. Built "
            "her core as Key Account Manager at Alibaba's Miravia (42 e-retail accounts, "
            "+30% GMV QoQ via pricing, assortment and promotions) and cut her teeth in "
            "confectionery FMCG at Mondelez (chocolate category planning, rolling "
            "forecasts, sell-in/sell-out). Strong on customer/joint business plans, "
            "stakeholder liaison across HQ/country/distributor lines, the customer "
            "digital journey and data-driven decisions. Native Spanish, fluent English "
            "(C1), already based in Dubai."
        ),
        "cl": {
            "opening_paragraph": (
                "Growing strategic e-retail accounts across priority markets — owning "
                "the budget plans and rolling forecasts, running assortment reviews with "
                "e-retailers and turning them into joint business plans that beat sales "
                "targets — is exactly the work I do today, so Perfetti Van Melle's "
                "E-Commerce Executive role for Growth Markets immediately drew me in. I "
                "currently lead Brand & E-Commerce for an FMCG portfolio across 50+ "
                "markets and built my career managing e-retail accounts on a top-5 "
                "marketplace, so the mandate reads like my day-to-day."
            ),
            "body_paragraph_1": (
                "At DoFreeze I grow strategic e-retail and quick-commerce accounts "
                "across the UAE (Noon, Talabat, Careem, Deliveroo) — onboarding, "
                "listings, promotional mechanics and retail execution — while owning the "
                "annual A&P/budget plans and monthly rolling forecasts jointly with "
                "distributors and country teams, running quarterly assortment reviews to "
                "optimise the mix, and safeguarding SKU availability and service levels. "
                "I build customer/joint business plans with joint KPIs, optimise the "
                "customer digital journey and digital shelf for conversion, and act as "
                "the liaison between HQ, country managers and external partners — the "
                "exact cross-functional wiring this role runs on."
            ),
            "body_paragraph_2": (
                "The foundation is directly relevant. At Alibaba's Miravia I managed and "
                "grew 42 e-retail key accounts, delivering +30% GMV quarter-on-quarter "
                "through pricing, assortment optimisation and targeted promotions, and "
                "owned the Flash Sales channel reporting to the CEO. Earlier, at Mondelez "
                "— a global confectionery leader — I ran sell-in/sell-out, rolling "
                "forecasts and promo-effectiveness analysis for the chocolate category, "
                "so Perfetti's confectionery world is familiar ground. I'm four-plus "
                "years in at manager level, and already based in Dubai I can bring that "
                "account-growth and forecasting discipline to your growth markets from "
                "day one."
            ),
            "closing_paragraph": (
                "I'd welcome the chance to discuss how my e-retail account growth, "
                "forecasting and quick-commerce experience would translate into "
                "Perfetti Van Melle's growth-market ambitions. Thank you for considering "
                "my application — I look forward to hearing from you."
            ),
        },
        "skills_match": [
            "Manages & grows strategic e-retail accounts today (DoFreeze UAE quick-commerce: Noon, Talabat, Careem, Deliveroo) + 42 accounts at Miravia, +30% GMV QoQ",
            "Owns annual budget plans + monthly rolling forecasts with distributors/country teams and runs quarterly assortment reviews — core JD tasks",
            "Confectionery-FMCG background (Mondelez chocolate category planning, rolling forecasts, sell-in/sell-out) directly relevant to Perfetti",
            "Customer/joint business plans (joint KPIs), SKU availability & service levels, customer digital journey / digital shelf, data-driven decisions",
            "HQ ↔ country ↔ distributor liaison; native Spanish, fluent English C1; already in Dubai",
        ],
        "missing_skills": [
            "Level: JD asks ~3 yrs 'Executive'; Paula is 4+ at Manager level — slightly senior to the band, not short of it (presented as hands-on account experience, not inflated)",
            "JD body says 'Position based in Lebanon' while the careers posting is tagged Dubai, AE (Dubai DMCC entity) — confirm the actual base before committing",
        ],
        "red_flags": [
            "IMPORTANT: the JD text states 'Position based in Lebanon' twice, even though the posting is tagged Location: Dubai, AE. Location field follows the Dubai tag per Guille's instruction — but confirm the real base with the recruiter; a Beirut base conflicts with Paula's employer-sponsored UAE residence visa and no-relocation preference.",
            "Salary not disclosed — confirm it clears the 20k AED/month floor.",
            "Nothing fabricated; no 'own visa / no sponsorship' claim (employer-sponsored residence visa).",
        ],
        "reasoning": (
            "Strong substance fit for Perfetti Van Melle's E-Commerce Executive (Growth "
            "Markets). The JD — grow strategic e-retail accounts to beat sales targets, "
            "annual budget plans, monthly rolling forecasts with country managers & "
            "distributors, quarterly assortment reviews, customer/joint business plans, "
            "SKU availability >85%, customer digital journey, HQ↔country↔partner liaison "
            "— maps almost point-for-point onto Paula's real work: DoFreeze UAE "
            "quick-commerce account growth + forecasting + assortment + budgets across "
            "50+ markets, and Miravia's 42-account e-retail book (+30% GMV QoQ). Bonus: "
            "confectionery-FMCG grounding at Mondelez. Honest caveats, surfaced not "
            "hidden: she is 4+ yrs at Manager level (slightly senior to this 'Executive' "
            "band, not short of it); and the JD text says 'based in Lebanon' while the "
            "posting is tagged Dubai — location follows the Dubai tag per instruction, "
            "but the real base must be confirmed given her UAE visa and no-relocation "
            "preference. Nothing fabricated; no visa/sponsorship claim."
        ),
    },
]


def make_job(role: dict) -> Job:
    return Job(
        id=role["id"],
        title=role["title"],
        company=COMPANY,
        location="Dubai, UAE",
        url=role["url"],
        source="perfetti_careers",
        description=role["job_description"],
        raw={
            "query": f"Perfetti Van Melle {role['title']} Dubai e-commerce FMCG",
            "function": "E-commerce / e-retail account management (FMCG confectionery)",
            "sector": "FMCG — Confectionery (Perfetti Van Melle Export Middle East & Africa DMCC)",
            "posted": role["posted"],
            "note": role["reasoning"],
        },
    )


def register_in_dashboard(role: dict, job: Job) -> None:
    path = settings.data_dir / "scored_jobs.json"
    if not path.exists():
        return
    jobs = json.loads(path.read_text(encoding="utf-8"))
    if any(j.get("id") == job.id for j in jobs):
        return
    jobs.insert(0, {
        "id": job.id,
        "title": job.title,
        "company": job.company,
        "location": job.location,
        "url": job.url,
        "source": job.source,
        "description": job.description,
        "salary_raw": "Not disclosed (Perfetti Van Melle Export ME&A DMCC — competitive FMCG package)",
        "salary_aed_min": None,
        "salary_aed_max": None,
        "posted_date": DATE_FOLDER,
        "raw": job.raw,
        "ai_score": role["ai_score"],
        "ai_tier": role["ai_tier"],
        "skills_match": role["skills_match"],
        "missing_skills": role["missing_skills"],
        "sector_fit": "FMCG / Confectionery e-commerce — YES (Paula's core sector)",
        "seniority_fit": "Executive-band role; Paula is 4+ yrs at Manager level — meets/exceeds the bar (confirm seniority & pay)",
        "red_flags": role["red_flags"],
        "ats_keywords": [
            "e-commerce", "ecommerce", "e-retail", "e-retailer platform", "e-retailers",
            "quick-commerce", "quickCommerce", "Noon", "Talabat", "Careem", "Deliveroo",
            "key account management", "account management", "e-retail accounts",
            "sales growth", "budgeted sales targets", "annual budget plans",
            "monthly rolling forecasts", "forecasting", "quarterly assortment reviews",
            "assortment", "product mix", "customer business plans", "joint KPIs",
            "SKU availability", "service levels", "distributor management",
            "country managers", "customer digital journey", "digital shelf",
            "conversion", "engagement", "CRO", "market trends", "consumer insights",
            "stakeholder management", "analytical skills", "sell-in", "sell-out",
            "ROI", "ROAS", "P&L", "FMCG", "confectionery", "Dubai", "UAE", "Middle East",
            "GCC", "MENA", "English",
        ],
        "reasoning": role["reasoning"],
        "scored_by": "manual:claude",
        "freshness": "fresh",
        "discovered_at": f"{DATE_FOLDER}T00:00:00+00:00",
        "status": "Reviewing",
    })
    path.write_text(json.dumps(jobs, ensure_ascii=False, indent=2), encoding="utf-8")


def _to_pdf_soffice(docx_path: Path) -> Path:
    """Convert DOCX -> PDF headlessly via LibreOffice (docx2pdf/Word fails on this Mac)."""
    soffice = shutil.which("soffice") or "/Applications/LibreOffice.app/Contents/MacOS/soffice"
    pdf_path = docx_path.with_suffix(".pdf")
    if Path(soffice).exists():
        try:
            subprocess.run(
                [soffice, "--headless", "--convert-to", "pdf", "--outdir",
                 str(docx_path.parent), str(docx_path)],
                check=True, capture_output=True, timeout=180,
            )
            if pdf_path.exists():
                docx_path.unlink(missing_ok=True)
                return pdf_path
        except Exception as exc:  # noqa: BLE001
            print("soffice conversion failed, falling back to docx2pdf:", exc)
    return cv._to_pdf(docx_path)


def _relocate_to_dated_folder(pos_dir: Path) -> Path:
    """Move output/<Company> - <Role>/ under output/<DATE_FOLDER>/."""
    dated_parent = settings.output_dir / DATE_FOLDER
    dated_parent.mkdir(parents=True, exist_ok=True)
    dest = dated_parent / pos_dir.name
    if pos_dir.resolve() == dest.resolve():
        return dest
    if dest.exists():
        for sub in pos_dir.iterdir():
            target = dest / sub.name
            if sub.is_dir():
                target.mkdir(parents=True, exist_ok=True)
                for f in sub.iterdir():
                    shutil.move(str(f), str(target / f.name))
            else:
                shutil.move(str(sub), str(target))
        shutil.rmtree(pos_dir, ignore_errors=True)
    else:
        shutil.move(str(pos_dir), str(dest))
    return dest


def build_one(role: dict) -> None:
    job = make_job(role)
    register_in_dashboard(role, job)

    cv_content = {
        "headline": role["headline"],
        "professional_summary": role["professional_summary"],
        "experience": SHARED_EXPERIENCE,
        **SHARED_SKILLS,
    }
    cv_docx = cv._fill_template(cv_content, job)
    cv_pdf = _to_pdf_soffice(cv_docx)
    print("OK_CV", cv_pdf)

    cl_docx = cl._fill_template(role["cl"], job, CONTACT)
    cl_pdf = _to_pdf_soffice(cl_docx)
    print("OK_CL", cl_pdf)

    pos_dir = cv_pdf.parent.parent
    final_dir = _relocate_to_dated_folder(pos_dir)
    print("OK_PACKAGE", final_dir)


def main() -> None:
    for role in ROLES:
        build_one(role)


if __name__ == "__main__":
    main()
