"""Manually inject the Opella Dubai/AMET contacts discovered via web research.

SerpAPI quota was exhausted during the automated run; this script pre-populates
the same files that ``find_contacts`` would have produced, so the dashboard
treats the contacts as if they came from the normal flow. Email candidates are
generated by ``email_finder.enrich_name`` using the confirmed corporate domain
``opella.com`` (verified via public ZoomInfo/RocketReach listings).

Source notes (manual research, May 2026):
  - Hossam Abo Ouf   - Country Head KSA & UAE, Opella  (sa.linkedin.com)
  - Shahab F. Mirza  - Trade & Revenue Mgmt Head AMET, Opella (UAE)
  - R. Murali Rao    - Head of Brand & Innovation AMET, Opella (Istanbul) **HM**
  - Ahsan Rizvi      - Digital Lead AMET, Opella
  - Duygu Cetin      - Opella (Turkey-side, AMET marketing team)
  - Rashmi Gupta     - prior AMET Brand & Innovation Head (alum)
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from career_ops.config import settings
from career_ops.contact_finder import Contact
from career_ops.email_finder import enrich_name

OPELLA_JOB_ID = "f324f5af0ff41e06"
OPELLA_DOMAIN = "opella.com"

CONTACTS_RAW = [
    {
        "name": "Murali Rao",
        "title": "Head of Brand & Innovation, AMET (Africa, Middle East, Turkey) — Opella",
        "linkedin_url": "https://tr.linkedin.com/in/murali-rao",
        "role_type": "Hiring Manager",
        "notes": (
            "Direct hiring authority for AMET brand roles. Stepped into the role "
            "April 2026 (succeeded Rashmi Gupta). 22+ years FMCG/CHC, prior at "
            "Reckitt and FrieslandCampina. Based in Istanbul — covers UAE."
        ),
    },
    {
        "name": "Hossam Abo Ouf",
        "title": "Country Head, KSA & UAE — Opella",
        "linkedin_url": "https://sa.linkedin.com/in/hossam-abo-ouf-75102b11",
        "role_type": "Hiring Manager",
        "notes": (
            "Country lead for the geography this role sits in. Likely sign-off "
            "on local marketing hires. Prior: Sanofi Head of Operations KSA & UAE, "
            "Boehringer Ingelheim, Pfizer. Based in Riyadh, oversees Dubai office."
        ),
    },
    {
        "name": "Shahab Fraz Mirza",
        "title": "Trade & Revenue Management Head, AMET — Opella",
        "linkedin_url": "https://ae.linkedin.com/in/shahab-fraz-mirza",
        "role_type": "Peer",
        "notes": (
            "Based in UAE — Opella Dubai office. Strong commercial counterpart "
            "to brand roles. Useful for a 'second touch' once warm with Murali."
        ),
    },
    {
        "name": "Ahsan Rizvi",
        "title": "Digital Lead, AMET — Opella",
        "linkedin_url": "https://www.linkedin.com/in/ahsanrizvi/",  # constructed; verify
        "role_type": "Peer",
        "notes": (
            "Digital lead for AMET — natural ally given Paula's UAE quick-commerce "
            "experience (Noon, Talabat, Careem). Email confirmed @opella.com via "
            "RocketReach."
        ),
    },
    {
        "name": "Rashmi Gupta",
        "title": "Former Head of Brand & Innovation AMET, Opella — now London",
        "linkedin_url": "https://www.linkedin.com/in/rashmi-gupta-674a283/",
        "role_type": "HR/Recruiter",  # treat as alumna/referral node
        "notes": (
            "Built AMET Brand & Innovation from scratch; handed off to Murali. "
            "Strong referral node — a warm intro from her to Murali would carry "
            "weight. Not the hirer."
        ),
    },
]


def main() -> None:
    print(f"[start] Injecting {len(CONTACTS_RAW)} Opella contacts manually...")

    contacts = [
        Contact(
            name=c["name"],
            title=c["title"],
            company="Opella",
            email=None,
            linkedin_url=c["linkedin_url"],
            role_type=c["role_type"],
            source="manual research (May 2026)",
        )
        for c in CONTACTS_RAW
    ]

    contacts_dir = settings.data_dir / "contacts"
    contacts_dir.mkdir(parents=True, exist_ok=True)
    contacts_path = contacts_dir / f"{OPELLA_JOB_ID}.json"
    meta_path = contacts_dir / f"{OPELLA_JOB_ID}.meta.json"
    emails_path = contacts_dir / f"{OPELLA_JOB_ID}.emails.json"

    contacts_path.write_text(
        json.dumps([c.to_dict() for c in contacts], indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    meta_path.write_text(
        json.dumps({
            "searched_at": datetime.now(timezone.utc).isoformat(),
            "count": len(contacts),
            "company": "Opella",
            "job_title": "Brand Manager",
            "source": "manual research (SerpAPI quota exhausted)",
        }, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    print(f"[saved] {contacts_path.name}")

    # ----- Email enrichment -----
    has_hunter = bool(settings.hunter_api_key)
    print(f"\n[emails] Hunter.io: {'enabled' if has_hunter else 'NOT set — patterns only'}")

    enriched = []
    for c, raw in zip(contacts, CONTACTS_RAW):
        candidates = enrich_name(c.name, OPELLA_DOMAIN, max_verify=3)
        primary = next((cand.email for cand in candidates if cand.status == "deliverable"), None)
        if not primary and candidates:
            primary = candidates[0].email
        record = {
            "name": c.name,
            "title": c.title,
            "linkedin_url": c.linkedin_url,
            "role_type": c.role_type,
            "notes": raw["notes"],
            "primary_email": primary,
            "primary_email_status": (
                "deliverable" if has_hunter and primary and any(
                    cand.email == primary and cand.status == "deliverable" for cand in candidates
                ) else "unverified"
            ),
            "all_candidates": [cand.to_dict() for cand in candidates],
        }
        enriched.append(record)
        print(f"  - {c.name}: {primary} ({record['primary_email_status']})")

    emails_path.write_text(json.dumps(enriched, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\n[saved] {emails_path.name}")
    print("Done.")


if __name__ == "__main__":
    main()
